Repository HiAvatar/frontend, pull requests merged in 2022-11, with the labels that each got.

#216 ♻️ refactor: AvatarVoiceMenu/#215
  src/components/projectTextEdit/AvatarVoiceMenu/index.tsx
  src/components/projectTextEdit/AvatarVoicePlayer/index.tsx
  src/components/projectTextEdit/RadioButton/index.tsx
  src/index.d.ts
  src/store/slices/optionSlice.ts
Labels: 🔨Refactor

#218 ♻️ refactor: VoiceControlMenu/#217
  src/components/projectTextEdit/VoiceControlMenu/index.tsx
  src/components/projectTextEdit/VoiceController/index.tsx
  src/index.d.ts
Labels: 🔨Refactor, 🏷️ Type

#221 🏷️ type: ProjectTextEdit/#220
  src/components/projectTextEdit/ProjectText/index.tsx
  src/components/projectTextEdit/TextEditList/index.tsx
  src/components/projectTextEdit/TextPlayer/index.tsx
  src/components/projectTextEdit/VoicePreviewPlayer/index.tsx
  src/store/slices/optionSlice.ts
Labels: 🎨 Structure / format, 🏷️ Type

#223 🐛 fix: TextPlayer/#222
  src/components/projectTextEdit/ProjectText/index.tsx
  src/components/projectTextEdit/TextEditList/index.tsx
  src/components/projectTextEdit/TextPlayer/index.tsx
  src/store/slices/optionSlice.ts
Labels: 🐛 BugFix

#225 🐛 fix: TextPlayer/#224
  src/components/projectTextEdit/TextPlayer/index.tsx
Labels: 🐛 BugFix
